[build]
  command = "git clone https://github.com/flutter/flutter.git -b stable --depth 1 && export PATH=\"$PATH:$PWD/flutter/bin\" && flutter doctor && flutter pub get && flutter build web --release --dart-define=SAFE_ROUTE_API_BASE_URL=https://saferoute-api-jk60.onrender.com"
  publish = "build/web"