services:
  - type: web
    name: saferoute-api
    runtime: python
    rootDir: backend
    buildCommand: "python -m pip install -r requirements.txt"
    startCommand: "gunicorn saferoute_api.wsgi:application --bind 0.0.0.0:$PORT"
    healthCheckPath: /health
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://saferoute-api-jk60.onrender.com"
      - key: DASHBOARD_USERNAME
        value: "admin"
      - key: DASHBOARD_PASSWORD
        value: "admin123"
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        value: "105928817756-d4pbc059dccu5o7jq63b6ep9mt4shdu9.apps.googleusercontent.com"
      - key: DATABASE_URL
        value: "postgresql://saferoute_4jd4_user:E7N8rz32diGbqHwbb95pj6BE4KCPSmr4@dpg-d8bem7jbc2fs73c9i7h0-a/saferoute_4jd4"
        sync: false
